// src/api/apiConfig.js

// export const BASE_URL = "https://biryanibet.desiapi.com";
export const BASE_URL = "https://okwin-admin-backend.biryanibet.com";

export const API_ENDPOINTS = {
  SIGNUP: "/api/user/signup",
  LOGIN: "/api/user/login",
  VERIFY_TOKEN: "/api/user/verify-token",
  GET_USER_DETAILS: (userId) => `/api/user/userDetails/${userId}`,
  UPDATE_USER_DETAILS: (userId) => `/api/user/updateUserDetails/${userId}`,
  CHANGE_PASSWORD: (userId) => `/api/user/changePassword/${userId}`,
  SEND_RESET_OTP: "/api/user/sendResetOTP",
  RESET_PASSWORD: "/api/user/resetPassword",
  FETCH_USER_BALANCE: (userId) => `/api/user/fetchUserBalance/${userId}`,
  GET_SETTINGS: "/api/getSettings",
  GET_USER_BETS: (userId) => `/api/getUserBets/${userId}`,
  GET_CATEGORIES: "/api/category/getCategories",
  GET_ALL_GAMES: "/api/game/getAllGames",
  GET_GAMES_BY_CATEGORY: (categoryId) => `/api/games/${categoryId}`,
  REDIRECT_ON_GAME: (userId) => `/api/user/redirect-on-game/${userId}`,
  GET_ATTENDANCE_STATUS: (userId) => `/api/user/getAttendanceStatus/${userId}`,
  CLAIM_DAILY_BONUS: "/api/user/claimDailyBonus",
  DAILY_ATTENDANCE_HISTORY: (userId) => `/api/user/getDailyAttendanceHistory?userId=${userId}`,
  TODAY_EARNING_CHART: "/api/user/todayEarningChat",
  CLAIM_GIFT_CODE: "/api/user/claimGiftCode",
  GET_CLAIMED_GIFT_CODES: (userId) => `/api/user/getClaimedGiftCodes/${userId}`,
  GET_FIRST_RECHARGE_BONUS: "/api/getFirstRechargeBonus",
  GET_BET_COMMISSION_LEVELS: "/api/getBetCommissionLevels",
  GET_DAILY_SALARY_SYSTEM: "/api/getDailySalarySystem",
  PAY_FROM_UPI: "/api/user/payFromUpi",
  GET_ALL_TRANSACTIONS: "/api/user/getAllTransactions",
  GET_REFERRAL_DASHBOARD:(userId) => `/api/user/getReferralDashboard/${userId}`,
  GET_REFERRAL_STATS: (userId) => `/api/user/getReferralStats/${userId}`,
  GET_REFERRAL_STATS_NEW: (userId) => `/api/user/getReferralStatsUsers/${userId}`,
  GET_LIVE_WITHDRAWALS: "/api/user/liveWithdrawal",
  GET_HOMEPAGE_DETAILS: "/api/getHomepageDetails",
  GET_DEPOSITE_RULES: "/api/admin/getDepositeRules",
  GET_WITHDRAWAL_RULES: "/api/admin/getWithdrawRules",
  GET_NOTIFICATIONS: "/api/admin/getAllNotifications",
  GET_PAYMENT_DETAILS: "/api/user/getPaymentDetails",
  ADD_BANK_DETAILS: "/api/user/addPaymentDetails",
  SELECT_BANK_DETAILS: "/api/user/selectPaymentDetails",
  GET_BET_STATISTICS:(userId)=> `/api/getBetStatistics/${userId}`,
  GET_UPI_LIST: "/api/getUpiList",
  GET_USDT_WALLET_LIST: "/api/getUsdtWalletList",
  CREATE_WITHDRAWREQUEST: "/api/user/createWithdrawRequest",
  CREATE_DEPOSITREQUEST: "/api/user/createDepositRequest",
  GET_DEPOSITE_BONUS: "/api/getDepositBonus",
};
